create table public.web_orders (
    id bigint generated by default as identity primary key,
    organization_id bigint not null references public.organizations(id) on delete cascade,
    bsale_checkout_id bigint not null,
    document_number bigint not null,
    cart_id bigint not null,
    pay_process text not null,
    order_status integer,
    payment_type_id bigint,
    shipping_method text,
    total numeric(14, 2) not null default 0,
    source_created_at timestamptz not null,
    received_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint web_orders_checkout_unique unique (organization_id, bsale_checkout_id)
);

create table public.web_order_items (
    id bigint generated by default as identity primary key,
    order_id bigint not null references public.web_orders(id) on delete cascade,
    bsale_cart_detail_id bigint not null,
    bsale_variant_id bigint not null,
    sku text not null,
    item_name text not null,
    quantity integer not null check (quantity > 0),
    picked_quantity integer not null default 0 check (picked_quantity >= 0 and picked_quantity <= quantity),
    constraint web_order_items_detail_unique unique (order_id, bsale_cart_detail_id)
);

create table public.print_jobs (
    id bigint generated by default as identity primary key,
    organization_id bigint not null references public.organizations(id) on delete cascade,
    order_id bigint not null references public.web_orders(id) on delete cascade,
    status text not null default 'pending' check (status in ('pending', 'processing', 'printed', 'failed')),
    attempts integer not null default 0 check (attempts >= 0),
    locked_by text,
    locked_at timestamptz,
    printed_at timestamptz,
    last_error text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint print_jobs_initial_order_unique unique (order_id)
);

create index web_orders_org_created_idx on public.web_orders (organization_id, source_created_at desc);
create index web_orders_pending_idx on public.web_orders (organization_id, source_created_at desc) where pay_process = 'success' and order_status = 2;
create index web_order_items_order_idx on public.web_order_items (order_id);
create index print_jobs_pending_idx on public.print_jobs (organization_id, created_at) where status in ('pending', 'failed');

alter table public.web_orders enable row level security;
alter table public.web_order_items enable row level security;
alter table public.print_jobs enable row level security;

revoke all on table public.web_orders from anon, authenticated;
revoke all on table public.web_order_items from anon, authenticated;
revoke all on table public.print_jobs from anon, authenticated;
revoke all on sequence public.web_orders_id_seq from anon, authenticated;
revoke all on sequence public.web_order_items_id_seq from anon, authenticated;
revoke all on sequence public.print_jobs_id_seq from anon, authenticated;

grant select, insert, update, delete on table public.web_orders to service_role;
grant select, insert, update, delete on table public.web_order_items to service_role;
grant select, insert, update, delete on table public.print_jobs to service_role;
grant usage, select on sequence public.web_orders_id_seq to service_role;
grant usage, select on sequence public.web_order_items_id_seq to service_role;
grant usage, select on sequence public.print_jobs_id_seq to service_role;
