create table if not exists public.printer_agents (
    id bigint generated by default as identity primary key,
    organization_id bigint not null references public.organizations(id) on delete cascade,
    device_name text not null,
    agent_version text,
    last_seen_at timestamptz not null default now(),
    last_error text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint printer_agents_organization_device_unique unique (organization_id, device_name)
);

create index if not exists printer_agents_org_seen_idx
    on public.printer_agents (organization_id, last_seen_at desc);

alter table public.printer_agents enable row level security;

revoke all on table public.printer_agents from public, anon, authenticated;
revoke all on sequence public.printer_agents_id_seq from public, anon, authenticated;
grant select, insert, update, delete on table public.printer_agents to service_role;
grant usage, select on sequence public.printer_agents_id_seq to service_role;
